name: network-app
services:
  - name: web
    type: web
    ports:
      - port: 8000
        http:
          paths:
            - /
    build:
      docker:
        dockerfile: Dockerfile
      command: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput --clear
        python manage.py migrate
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: project4.settings
      - name: PYTHONPATH
        value: /workspace
    routes:
      - path: /
        port: 8000
    scaling:
      min: 1
      max: 1
    resources:
      cpu: 200m
      memory: 512Mi
      disk: 1Gi
