# Generated by Django 6.0.1 on 2026-01-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment'),
    ]

    operations = [
    ]
