# Generated by Django 6.0.1 on 2026-01-14 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20260114_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_conversations',
            field=models.ManyToManyField(blank=True, related_name='hidden_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
