# Generated by Django 6.0.1 on 2026-01-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_hidden_conversations'),
    ]

    operations = [
    ]
