# Generated by Django 6.0.1 on 2026-01-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20260114_2237'),
    ]

    operations = [
    ]
