# Generated by Django 6.0.1 on 2026-01-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_comment_media_comment_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
