# Generated by Django 6.0.1 on 2026-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_comment_options_remove_comment_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
